apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-native
  namespace: example
spec:

  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: k8s-native
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
