apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-native
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-native
  template:
    metadata:
      labels:
        app: k8s-native
    spec:
      containers:
        - name: k8s-native
          image: k8s-native
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 150m
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      restartPolicy: Always
      imagePullSecrets:
        - name: test

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-native
spec:
  selector:
    app: k8s-native
  ports:
    - port: 8080
  type: ClusterIP