apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: stg-

components:
  - ../../components/affinity

replicas:
  - name: k8s-native
    count: 5

commonLabels:
  stage: stg
  app: k8s-native
