apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prd1-

components:
  - ../../components/affinity

replicas:
  - name: k8s-native
    count: 3

commonLabels:
  stage: prd
  app: k8s-native
